table d_customers
	lineageTag: ec50860e-58f9-4bf0-918d-d7cdcffab683

	column category
		dataType: string
		lineageTag: b9de7dbe-3bfb-4d5a-8316-6cfe309a5df7
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 33478e5f-18af-4d49-bea6-a7455ad75fec
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 7c53c0a2-d92c-4b06-b800-c2f308fff61f
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = User

	partition d_customers = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\caioc\OneDrive\Documentos\arquivos_drive\portfolio\sales_analysis\data\targets.xlsx"), null, true),
				    Sheet1_Sheet = Fonte{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"customer_id", Int64.Type}, {"category", type text}, {"city", type text}, {"monthly revenue target", Int64.Type}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"monthly revenue target"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

